{
 "title": "Resource Usage By Namespace",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "query_result(count(kube_namespace_labels{label_monitoring_key='middleware'}) by (namespace))"
   },
   {
    "name": "cluster",
    "label": "osd_cluster",
    "query": "query_result(count(ALERTS) by (osd_cluster))"
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~'$namespace', container='', osd_cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~'$namespace',container='', osd_cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~'$namespace',container='', osd_cluster=~\"$cluster\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~'$namespace',container='', osd_cluster=~\"$cluster\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', osd_cluster=~\"$cluster\"}) by (pod)"
    }
   ]
  }
 ]
}